### ISSUE TITLE
Division by 0 causes non-AVR mcus hang

### ISSUE THREAD

**Issue by gdiciocco** [ridiculousfish/libdivide#112]
Division by 0 on non-AVR mcus causes libdivide call abort() which ends up in a noreturn 

https://github.com/noisymime/speeduino/issues/1162

**Comment by kimwalisch** [comment]
This is correct behavior.

If you don't like this behavior you can add an if check to your code to handle 0 dividers differently (before using libdivide).

**Comment by adbancroft** [comment]
We discussed this on the Speeduino Discourse and pretty much agreed this is a bug in client code, with no reasonable fix on the libdivide end.

I think this can be closed @gdiciocco ?

**Comment by gdiciocco** [comment]
Sure, I raised the issue because AVR is the only microcontroller family receiving a custom treatment. If this matches the plans (and at the same time makes sense as we saw on discord) no reason to keep the issue open anymore. Ty!
