### ISSUE TITLE
Remove AppVeyor from GitHub settings

### ISSUE THREAD

**Issue by kimwalisch** [ridiculousfish/libdivide#123]
@ridiculousfish Here are the instructions for how to remove AppVeyor CI testing from the GitHub settings (of the libdivide repo). Without this all new commits will be marked as failed AppVeyor CI tests.

1. **Unlink AppVeyor from your GitHub repository:**
   - Go to [AppVeyor](https://www.appveyor.com/) and log in.
   - Navigate to your **Projects** page.
   - Find the project linked to your GitHub repository.
   - Click the project, and then go to the **Settings** tab.
   - Scroll down and select **Delete** to remove the AppVeyor project.

2. **Revoke AppVeyor’s access to your GitHub account:**
   - Go to GitHub and click on your profile picture, then go to **Settings**.
   - In the left sidebar, select **Applications**.
   - Under **Authorized OAuth Apps**, find **AppVeyor** and click **Revoke Access**.

3. **Remove AppVeyor webhooks from GitHub repository:**
   - Go to your repository on GitHub.
   - Click on **Settings**.
   - In the left sidebar, click **Webhooks**.
   - Look for any webhook related to AppVeyor and delete it.

Once you’ve unlinked AppVeyor and removed the webhooks, GitHub will stop showing the failed AppVeyor checks for new commits.

**Comment by ridiculousfish** [comment]
Should be removed. Thanks for the detailed instructions!
