### ISSUE TITLE
#pragma warning( suppress : 4146 )

### ISSUE THREAD

**Issue by kimwalisch** [ridiculousfish/libdivide#16]
I saw your [code](https://github.com/ridiculousfish/libdivide/blob/branchfree/libdivide.h#L1232):

```C++
        uint32_t absD = 1U << shift;
        if (more & LIBDIVIDE_NEGATIVE_DIVISOR) {
#if LIBDIVIDE_VC
#pragma warning( suppress : 4146 )
            absD = -absD;
#else
            absD = -absD;
#endif      
        }
```

I came across the same issue a few years ago and found a shorter solution (which I use [here](https://github.com/kimwalisch/primesieve/blob/master/src/apps/console/calculator.hpp#L385)):

```C++
uint32_t absD = 1U << shift;
if (more & LIBDIVIDE_NEGATIVE_DIVISOR) {
    absD = absD * (uint32_t)-1;
}
```

I guess the compiler will generate the same code but you avoid the ugly pragma.

**Comment by ridiculousfish** [comment]
Nice tip! Thanks!!
