### ISSUE TITLE
Use __umulh()/__mulh() on MSVC

### ISSUE THREAD

**Issue by zekyll** [ridiculousfish/libdivide#19]
The functions libdivide__mullhi_u64/libdivide__mullhi_s64 can be implemented much faster on MSVC with __umulh()/__mulh() intrinsics. They have the exact same signature so it's a very easy modification and should be supported on all MSVC versions.

**Comment by ridiculousfish** [comment]
Cool! Did you happen to check how MSVC is currently compiling these - i.e. are the intrinsics actually faster?

**Comment by zekyll** [comment]
It does compile to single instruction on x64 at least and it is significantly faster.

**Comment by ridiculousfish** [comment]
Oh I just noticed what the current implementation is. Yes, let's switch to these when available.
