### ISSUE TITLE
modular multiplication

### ISSUE THREAD

**Issue by PoslavskySV** [ridiculousfish/libdivide#26]
Is there a simple way to implement modular multiplication of two 64-bit integers modulus other 64-bit integer with preconditioning? I mean the method like:

    uint64_t mulmod_u64(uint64_t a, uint64_t b, const struct libdivide_u64_t *denom) { ... }

which returns ``(a * b) % denom`` .

**Comment by ridiculousfish** [comment]
Great question. Is the concern overflow in the intermediate calculation `a*b`, or is it achieving better performance? (Or both?). Also, is it a typo that the return type is unsigned but parameters are unsigned, or is that part of it?

**Comment by PoslavskySV** [comment]
Yes, both better performance and overflow in the intermediate calculation are important. I've fixed the typo in the question -- the return type is also unsigned. (btw, as far as I understand, if the performance is not important one can use `libdivide_128_div_64_to_64` method).   Thanks!

**Comment by ridiculousfish** [comment]
You may be interested in [my related SO question](http://stackoverflow.com/questions/38925522/multiplying-integer-by-rational-without-intermediate-overflow). Do we know anything about `denom` here - can we place an upper or lower bound, is it prime, etc?

**Comment by PoslavskySV** [comment]
We know that `denom` is prime and `2 <= number_of_bits(denom) <= 62`, can this help?

**Comment by ridiculousfish** [comment]
With the modulus prime and used repeatedly, you might be able to apply Montgomery reduction. That's the best I can think of.

**Comment by PoslavskySV** [comment]
I also came up with this; just hoped that it is possible to reuse libdivide code. Thanks!
