### ISSUE TITLE
Question: Adding this to Python, Go, Nim, Crystal etc.

### ISSUE THREAD

**Issue by DonaldTsang** [ridiculousfish/libdivide#44]
Would adding this to Python be a good idea? That way integer divmod would be faster (unless they already did it with Python 3)
Also, adding LibDivide to Go, Nim, Crystal and other languages would make the code base better.
Considering Go is supposed to be the fast code replacement of java, Nim can compile to C/C++ and JS, and Crystal can compile to C.

**Comment by ridiculousfish** [comment]
libdivide does not accelerate arbitrary divisions, but specifically cases where you repeatedly divide by the same divisor.

I think it would be awesome to integrate libdivide's algorithms more languages, but it doesn't make sense to do under this project. Rather it should be done in the typical way for each language and its corresponding package managers - [example](https://code.dlang.org/packages/divide).

Closing for that reason, thanks for filing!
