### ISSUE TITLE
size_t support

### ISSUE THREAD

**Issue by william-silversmith** [ridiculousfish/libdivide#58]
Hi,

This might be a naïve question, but I had trouble compiling some C++ code using the admittedly variable width `size_t`. It compiled on Ubuntu using g++ but failed on Mac OS using clang.

```
././libdivide.h:1951:63: error: no type named 'divider' in '(anonymous namespace)::libdivide::libdivide_internal::dispatcher<unsigned long, -1>'
    typedef typename libdivide_internal::dispatcher<T, ALGO>::divider div_t;
```

I changed my code to use `uint64_t`, which is fine for my use case. Is it possible to support `size_t`? No urgency here, just curious.

Thanks!
Will

**Comment by kimwalisch** [comment]
Thanks for your feedback.

Someone else posted a pull request a few days ago which I think would also fix your issue. But that pull request needs to be improved a little and I am currently on holiday. So we will definitely fix this issue but it will take some time.

**Comment by william-silversmith** [comment]
Thanks, that's really helpful! Thanks so much for this very cool library. :)

**Comment by kimwalisch** [comment]
@william-silversmith: Do you need C++98 support? Or would you be OK with a C++11 only fix?

**Comment by william-silversmith** [comment]
At least for me, I've been writing all of my code to a C++11 standard.
Thanks for your help!

Will

**Comment by kimwalisch** [comment]
Fixed by https://github.com/ridiculousfish/libdivide/commit/623f9be3e406712be192e75833019f790aef8a51

Thanks for your feedback!

**Comment by william-silversmith** [comment]
Awesome! Thank you I'll check it out.

Will
