### ISSUE TITLE
Consider automatically defining LIBDIVIDE_SSE2 et al

### ISSUE THREAD

**Issue by AlexGuteniev** [ridiculousfish/libdivide#63]
For Visual Studio:
 * /arch compiler option sets target processor and enables compiler to use corresponding instructions
 * /arch:IA32, /arch:SSE, /arch:SSE2, /arch:AVX, /arch:AVX2, /arch:AVX512 options available
 * x86 is by default /arch:SSE2
 * x64 is always at least /arch:SSE2, it cannot be /arch:SSE or /arch:IA32
 * The value passed to arch is exposed as `_M_IX86_FP` predefined macro (distinguish SSE2), `__AVX__`, `__AVX2__`, and others. See [Predefined macros](https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019)

So libdivide could have something like:
```
#if defined(_MSC_VER) && defined(__AVX2__) 
#define LIBDIVIDE_AVX2
```

Maybe other compilers also expose compilation against specific instruction set via preprocessor

**Comment by kimwalisch** [comment]
We already discussed in https://github.com/ridiculousfish/libdivide/issues/34 why we don't enable SSE2 by default.
