### ISSUE TITLE
Critics of Algorithm D

### ISSUE THREAD

**Issue by ValZapod** [ridiculousfish/libdivide#67]
Look here:
https://skanthak.homepage.t-online.de/division.html#libdivide

You did fix the biggest problem in https://github.com/ridiculousfish/libdivide/commit/5e545305783b867367915e4820b2a78062f9a3c3

But others are still there. Also you can read https://news.ycombinator.com/item?id=26562819

You can also use https://gmplib.org/~tege/division-paper.pdf as used in GMP (GNU Multiple Precision Arithmetic Library).

**Comment by ridiculousfish** [comment]
Man what an asshole.

**Comment by ValZapod** [comment]
> Man what an asshole.

It is not my article, I am russian.

**Comment by ridiculousfish** [comment]
Yes, understood, thank you for filing! I was referring to the blog author.

**Comment by ValZapod** [comment]
LOL, you even fixed a bug in clang. Bravo. D:)

**Comment by ridiculousfish** [comment]
Gonna publish my new algorithm tomorrow or perhaps later tonight!
