### ISSUE TITLE
libdivide.h:1691:59: error: ‘numers’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by useperl** [ridiculousfish/libdivide#90]
Hello,
when I try to build libdivide with gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) under Ubuntu 20.04, I get the following error:

```make
...
[ 30%] Building CXX object CMakeFiles/benchmark.dir/test/benchmark.cpp.o
In file included from /home/hb/proj/libdivide/test/benchmark.h:24,
                 from /home/hb/proj/libdivide/test/benchmark.cpp:16:
/home/hb/proj/libdivide/libdivide.h: In function ‘uint64_t sum_quotients_vec(const random_numerators<IntT>&, const Divisor&) [with IntT = short unsigned int; Divisor = libdivide::divider<short unsigned int, libdivide::BRANCHFULL>]’:
/home/hb/proj/libdivide/libdivide.h:1691:59: error: ‘numers’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
 1691 |         pTarget[loop] = libdivide_##Algo##_do(pSource[loop], denom); \
      |                                                           ^
...
```

I just run `cmake .`, then `make`, and then get the error. (Running `make -j` instead of just `make` gives the same error). Am I doing anything wrong? What's the easiest way to fix or work around? I'm just trying to get a working benchmark binary.
I tried building current `master` branch...
```
commit b785c76ea6cf3b85108324f12cd4d16f0e75563e (HEAD -> master, origin/master, origin/HEAD)
Author: Kim Walisch <kim.walisch@gmail.com>

    Delete CHANGELOG.md
```
... as well as release 5.0:
```
commit b322221677351ebb11f0a42fe9a9a2794da5bfe5 (tag: 5.0)
Author: ridiculousfish <corydoras@ridiculousfish.com>

    Stop passing multiple targets to cmake build
```
with the same error

**Comment by adbancroft** [comment]
I followed your steps & can reproduce. Only happens in Release configuration - `cmake . -DCMAKE_BUILD_TYPE=Debug` works.

**Comment by adbancroft** [comment]
Looks like GCC on x86 has some [vector intrinsics](https://gcc.gnu.org/onlinedocs/gcc/Vector-Extensions.html#Vector-Extensions) that might be interfering. Or possibly alignment issues.

In the meantime `cmake . -DLIBDIVIDE_SSE2=OFF -DLIBDIVIDE_AVX2=OFF -DLIBDIVIDE_AVX512=OFF -DLIBDIVIDE_NEON=OFF` should work.
